apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-storage

resources:
  - postgres.yaml
  - minio.yaml
  # minio-uploader.yaml is applied separately after minio is ready
