---
apiVersion: v1
kind: Namespace
metadata:
  name: data-ingress
  labels:
    name: data-ingress
    layer: ingestion
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-storage
  labels:
    name: data-storage
    layer: storage
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-pgbouncer
  labels:
    name: data-pgbouncer
    layer: storage
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-lakekeeper
  labels:
    name: data-lakekeeper
    layer: catalog
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-trino
  labels:
    name: data-trino
    layer: query
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-kafka
  labels:
    name: data-kafka
    layer: streaming
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-arroyo
  labels:
    name: data-arroyo
    layer: stream-processing
    app: marsfx
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-dagster
  labels:
    name: data-dagster
    layer: orchestration
    app: marsfx
